# Generated by Django 4.2.25 on 2025-10-22 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listingimage",
            index=models.Index(
                fields=["listing"], name="listing_ima_listing_d8bfd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["category"], name="listings_categor_a280cc_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="listings_status_c3eaec_idx"),
        ),
    ]
